# 是否启动立马执行
startup: true
# 连接服务器客户端数量
clients: 5
# 本地操作磁盘数量
goroutines: 50
# 自定义操作代码(空表示全部)
codes:
   - sz000001
   - sh600000
   - bj920000

# 自定义指数代码
# index:
#   - sh000001

# 数据库配置
database:
  type: sqlite # mysql, influxdb

# 数据存储路径
dir:
  base: ./data
  database: database

# 通知配置
notice:
  serverChan:
    sendKey:
    message: 任务完成