clients: 3
coroutine: 3
startup: true
spec: "0 1 15 * * *"
codes:
#  - sh000001  # 上证指数
#  - sz399001  # 深证成指
#  - sz399006  # 创业板指
#  - sh000016  # 上证50
#  - sh000688  # 科创50
#  - sh000010  # 上证180
#  - sh000300  # 沪深300
#  - sh000905  # 中证500
#  - sh000852  # 中证1000
#  - sh000932  # 中证消费指数,
#  - sh000827  # 中证环保指数,