coroutine: 10
filename: "./data/20060102-150405.csv"
spec:
  - "0 26 9 * * *"
  - "0 31 9 * * *"
  - "0 1 15 * * *"
  - "0 35 15 * * *"
  - "30 36 20 * * *"
orderTime:
  - "0931"
  - "0932"
  - "1500"
orderTime2:
  - "0930"